### ISSUE TITLE
add possibilty to name the iSee entity (or disabling it by not naming it)

### ISSUE THREAD

**Issue by Bascht74** [echavet/MitsubishiCN105ESPHome#18] opened 2024-01-31 23:11 UTC
Right now for all my devices an iSee sensor is created: 
<img width="333" alt="image" src="https://github.com/echavet/MitsubishiCN105ESPHome/assets/66269310/0b658216-5251-4a1b-84d8-fc789c7b01dc">

Other than the vanes for frequency sensors it is not possible to name the sensor. 
Not naming should do that the iSee sensor is not getting created in HA...

This is the last little thing I found so far. 
I will now change all other 5 devices (three different types) to the new version.

**Comment by echavet** [comment] 2024-02-01 16:42
I don't think it causes troubles in home assistant because sensors are entities attached to a single device and with a unique ID. Well I'm not absolutely sure of that!
However. I committed the update but couldn't really test it because I don't have any isee sensor on my heatpumps.

**Comment by disruptivepatternmaterial** [comment] 2024-02-02 01:06
related to this...is it possible to turn the iSee to a switch? I want to reenable it after it seems to get disabled sometimes.

**Comment by echavet** [comment] 2024-02-02 10:09
I think this is a readonly sensor. 
Unless I did not understand the sensor utility, to me it makes no sense to turn it into a button as it is used to detect persons in the room. 
I might be wrong, my heatpumps do not have such sensors.

**Comment by echavet** [comment] 2024-02-02 10:29
or I see what you mean now.
You want to enable/disable the use of the sensor by your modules?
Well I don't actually know what packet to send to the heatpump for that. I think SwiCago did not implement this in his lib.

**Comment by disruptivepatternmaterial** [comment] 2024-02-02 15:38
I figured that might be the case 👍🏽 I think iSee if uncommon (or has been) in North America. I have seen them in Europe and Asia for a long time. It was hard to get one here in America, but I have 1. At some point I am going to retrofit to ceiling cassettes with iSee, but for now only have 1. If I can provide logs to help (if you are interested) I'll send along, but otherwise it is really minor. I can always turn it back on with the remote.

**Comment by echavet** [comment] 2024-02-03 11:56
OK thanks for your feedback. 
Do you think there is an issue with the iSee sensor ?
Because I'd gladly watch your logs but I'm not really sure I understand what the problem is:
Do you mean the MitsubishiCN105ESPHome component does switch the iSee feature **OFF** on your unit, and that you have to set it back **ON** with the remote ?

**Comment by disruptivepatternmaterial** [comment] 2024-02-05 18:28
yeah something is getting lost here :) I think the problem is I tinker late and night or early in the morning HAHAHA I'll try to be more detailed: but I will send along logs when I can. So what happens is I want iSee most of the time because this unit is in my office, which is not used most of the day/night. But when I manually change the temp using your code it turns off iSee, so when I come back into the office in the morning I have to turn it back on with the remote. Ideally I would love to automate this. So I can make an automation that turns iSee back on say at 8am every workday.

**Comment by echavet** [comment] 2024-02-05 18:37
did you try other implementations (from other reposirories)? Do they disable the unit iSee sensor too ?

**Comment by disruptivepatternmaterial** [comment] 2024-02-05 20:11
I have tried them all. To my understanding none of them even are aware of iSee, but the kumo adapter (when it decided to randomly work) would. I have an idea here: I think the bit you are reporting on is if the unit is currently using iSee. Not if it is enabled. Why do I think this? Because it would seem when I am in the office it is 1, when I am not it is 0, but I will keep testing this - Ill not it as I go in and out of the room through the day.

**Closed** 2024-02-06 08:13 UTC
